services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./templates:/app/templates
      - ./tests:/app/tests
    env_file:
      - .env
    tty: true
    stdin_open: true
