import os
import pandas as pd
from pathlib import Path
from src.utils.logger import get_logger

logger = get_logger(__name__)

class LLMExcelGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, md_path: str, json_path: str):
        """
        Markdown/JSONとLLMを用いてExcelを生成するモック処理。
        実際には OpenAI/Anthropic API を呼び出してレイアウトを解釈させる。
        """
        base_name = Path(md_path).stem
        logger.info(f"Generating Excel from {md_path} and {json_path}")
        
        excel_path = self.output_dir / f"{base_name}.xlsx"
        
        # モックで単純なExcelファイルを作成
        df = pd.DataFrame({
            "Column A": ["Data 1", "Data 2"],
            "Column B": ["Value 1", "Value 2"],
            "Note": ["Generated by LLM mock", "Source: MD/JSON"]
        })
        
        df.to_excel(excel_path, index=False)
        
        logger.info(f"Excel file generated at: {excel_path}")
        return str(excel_path)
